### ISSUE TITLE
windows 客户端读取失败了

### ISSUE THREAD

**Issue by feiyang666** [rmb122/rogue_mysql_server#1]
直接异常了

**Comment by rmb122** [comment]
可以说一下具体的库和版本么，这种情况一般是没有打开 `--local-infile` 选项，导致请求和回复不同步，而且是无法利用漏洞的，所以暂时没有做上适配，之后有空会加上。

**Comment by rmb122** [comment]
fixed in https://github.com/rmb122/rogue_mysql_server/commit/49718e216475994a8d055db1fc9e200863ce7ae9
