### ISSUE TITLE
detectCustomCollations链

### ISSUE THREAD

**Issue by mssky9527** [rmb122/rogue_mysql_server#12]
师傅好像我试了下在这篇文章中（https://tttang.com/archive/1877/#toc_1detectcustomcollations）提到的detectCustomCollations链无法利用

**Comment by rmb122** [comment]
detectCustomCollations 的利用方式和 ServerStatusDiffInterceptor 的利用方式是不同的, 需要做相应适配, https://github.com/rmb122/rogue_mysql_server/blob/6b6b1f89401bbba6030e3c69e103e0ce67bb5396/main.go#L236-L265 目前是只支持 ServerStatusDiffInterceptor

**Comment by mssky9527** [comment]
好的，期待师傅的适配
