### ISSUE TITLE
部分库以及失效，无法编译

### ISSUE THREAD

**Issue by kaikaix** [rmb122/rogue_mysql_server#13]
go: downloading vitess.io/vitess v3.0.0-rc.3.0.20190602171040-12bfde34629c+incompatible
go: downloading golang.org/x/net v0.0.0-20200602114024-627f9648deb9
rogue_mysql_server imports
        vitess.io/vitess/go/sqltypes: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        golang.org/x/net/context: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        vitess.io/vitess/go/bucketpool: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        vitess.io/vitess/go/netutil: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        vitess.io/vitess/go/stats: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        vitess.io/vitess/go/sync2: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        vitess.io/vitess/go/tb: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        vitess.io/vitess/go/vt/proto/binlogdata: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        vitess.io/vitess/go/vt/proto/query: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        vitess.io/vitess/go/vt/proto/replicationdata: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        vitess.io/vitess/go/vt/proto/vtrpc: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        vitess.io/vitess/go/vt/sqlparser: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        vitess.io/vitess/go/vt/vterrors: zip: not a valid zip file
rogue_mysql_server imports
        rogue_mysql_server/mysql imports
        vitess.io/vitess/go/vt/vttls: zip: not a valid zip file

**Comment by rmb122** [comment]
我本地是可以编译的, 是不是代理没设置好或者其他网络问题 🤔

```
# rmb122 @ rmb122-laptop in /tmp/rogue_mysql_server on git:master ✔ [12:59:19]
$ sudo docker run -v $PWD:/src --rm -it golang
Unable to find image 'golang:latest' locally
llatest: Pulling from library/golang
bc0734b949dc: Pull complete
b5de22c0f5cd: Pull complete
917ee5330e73: Pull complete
bed956b3d08c: Pull complete
76a498520fee: Pull complete
49fe8346018f: Pull complete
Digest: sha256:672a2286da3ee7a854c3e0a56e0838918d0dbb1c18652992930293312de898a6
Status: Downloaded newer image for golang:latest
root@c807c3964dbf:/go# cd /src
root@c807c3964dbf:/src# ls
LICENSE.txt  Makefile  README.md  README_EN.md	config.yaml  go.mod  go.sum  loot  main.go  mysql  rogue_mysql_server  test
root@c807c3964dbf:/src# go env -w 'GOPROXY=https://goproxy.cn,direct'
root@c807c3964dbf:/src# go build -buildvcs=false
go: downloading gopkg.in/yaml.v2 v2.2.5
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading vitess.io/vitess v3.0.0-rc.3.0.20190602171040-12bfde34629c+incompatible
go: downloading golang.org/x/net v0.0.0-20200602114024-627f9648deb9
go: downloading golang.org/x/sys v0.0.0-20220928140112-f11e5e49a4ec
go: downloading github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: downloading google.golang.org/grpc v1.30.0
go: downloading github.com/golang/protobuf v1.4.2
go: downloading google.golang.org/protobuf v1.23.0
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
root@c807c3964dbf:/src# ls
LICENSE.txt  Makefile  README.md  README_EN.md	config.yaml  go.mod  go.sum  loot  main.go  mysql  rogue_mysql_server  test
root@c807c3964dbf:/src# ./rogue_mysql_server
INFO[2023-12-29 05:07:02] Server started at [0.0.0.0:3306]
^C
```
