### ISSUE TITLE
Go1.15 运行失败

### ISSUE THREAD

**Issue by RedTeamWing** [rmb122/rogue_mysql_server#4]
# command-line-arguments
./main.go:194:43: undefined: schemaToFields
./main.go:194:58: undefined: Schema
./main.go:198:37: undefined: rowToSQL
./main.go:198:46: undefined: Row
./main.go:203:18: undefined: getMysqlVars

**Comment by rmb122** [comment]
`go build` 或者 `go build main.go sql.go`, 直接 `go build main.go` 会缺少 sql.go 里面定义的函数
