### ISSUE TITLE
不会按照顺序依次读取文件

### ISSUE THREAD

**Issue by RedTeamExp** [rmb122/rogue_mysql_server#5]
配置file_list: ["/etc/passwd", "C:/boot.ini"]

使用windows客户端连接mysql,只会读取/etc/passwd，文件不存在就不会继续读取c:/boot.ini文件

![image](https://user-images.githubusercontent.com/74718678/107136087-45cd4700-693b-11eb-955a-1ec47d851e26.png)

**Comment by rmb122** [comment]
因为部分客户端没有实现一次读取多个文件的功能, 所以这个按顺序读取是每 SELECT 一次会尝试读下一个文件, 你可以尝试手动多输几次 SELECT 就会按顺序读了
