### ISSUE TITLE
读取文件不存在导致程序卡住

### ISSUE THREAD

**Issue by Saber-CC** [rmb122/rogue_mysql_server#6]
config.yaml中file_list: ["/etc/passwd", "C:/boot.ini",”xxxxxx“]，当某个文件不存在时读取导致程序卡住以至于无法读取后面的文件，尝试跳过没有解决，请问有没有好的解决思路

time="2021-08-04 14:01:56" level=info msg="Server started at [0.0.0.0:3306]"
time="2021-08-04 14:02:31" level=info msg="New client from addr [[::1]:1037] logged in with username [root], ID [1]"
time="2021-08-04 14:02:31" level=info msg="==== ATTRS ===="
time="2021-08-04 14:02:31" level=info msg="[_thread]: [12980]"
time="2021-08-04 14:02:31" level=info msg="[_platform]: [AMD64]"
time="2021-08-04 14:02:31" level=info msg="[_client_version]: [10.1.46]"
time="2021-08-04 14:02:31" level=info msg="[_os]: [Win64]"
time="2021-08-04 14:02:31" level=info msg="[_client_name]: [libmysql]"
time="2021-08-04 14:02:31" level=info msg="[_pid]: [21632]"
time="2021-08-04 14:02:31" level=info msg="==============="
time="2021-08-04 14:02:31" level=info msg="Client from addr [[::1]:1037], ID [1] try to query [SET NAMES utf8mb4]"
time="2021-08-04 14:02:31" level=info msg="Now try to read file [/etc/passwd] from addr [[::1]:1037], ID [1]"
time="2021-08-04 14:02:31" level=info msg="Read failed, file may not exist in client"
time="2021-08-04 14:02:31" level=info msg="Client from addr [[::1]:1037], ID [1] try to query [SHOW VARIABLES LIKE 'lower_case_%']"
time="2021-08-04 14:02:31" level=info msg="Now try to read file [C:/boot.ini] from addr [[::1]:1037], ID [1]"
time="2021-08-04 14:02:31" level=info msg="Read failed, file may not exist in client"
time="2021-08-04 14:02:31" level=info msg="Client from addr [[::1]:1037], ID [1] try to query [ SHOW VARIABLES LIKE 'sql_mode']"

**Comment by rmb122** [comment]
文件不存在的话应该是不会卡住客户端的, 可能是你需要手动执行一下 `SELECT 1` ? 因为这个 file_list 实际上不是直接向客户端请求 list 中的一堆文件, 而是客户端每查询一个语句后向按顺序向客户端请求文件. 这样实现的原因是因为部分客户端没有实现一次读取一堆文件的功能, 会卡住客户端.
