### ISSUE TITLE
似乎不管读取什么文件都返回“Read failed, file may not exist in client”？

### ISSUE THREAD

**Issue by lesion1999** [rmb122/rogue_mysql_server#7]
不论读取的文件是什么似乎都会返回“Read failed, file may not exist in client”，我是用的是在命令行连接rogue mysql server。

**Comment by rmb122** [comment]
部分系统/发行版命令行需要使用 `--local-infile` 选项启用 `LOAD DATA LOCAL INFILE` 功能  
可以参考 https://github.com/rmb122/rogue_mysql_server/blob/master/test/native/test.sh
